export interface Datos{
Consecutivo: number,
Anio: number,
TipoEvento: string,
Evento: string,
FechaConvocatoria: string,
FechaFallo: string,
TipoBien: string,
subtipoBien: string,
Lote: number,
DescripcionLote: string,
Estado: string,
EntidadTransferente: string,
PrecioSalidaMontoEnMXN: number,
Resultado: string,
PrecioVentaMontoEnMXN: string,
EstadoComprador: string,
}